# Generated by Django 3.0 on 2025-06-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_Name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('photo', models.CharField(default='', max_length=100)),
                ('pin', models.CharField(default='', max_length=10)),
                ('DOB', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('post', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('Experience', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=200)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Caretaker')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=100)),
                ('level', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Word_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('Level', models.CharField(default='', max_length=100)),
                ('Rearrange_word', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_time', models.TimeField()),
                ('To_time', models.TimeField()),
                ('Date', models.DateField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pill_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('pill', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Pill_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('photo', models.CharField(max_length=500)),
                ('title', models.CharField(default='', max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=500)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='motion_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default='2001-01-01')),
                ('Feedback', models.CharField(max_length=100)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='Fall_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Login'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('CARETAKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Caretaker')),
            ],
        ),
        migrations.AddField(
            model_name='caretaker',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Login'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Patient')),
                ('SCHEDULE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_project.Schedule')),
            ],
        ),
    ]
