# Generated by Django 3.0 on 2025-06-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fall_notification',
            name='date',
            field=models.DateField(),
        ),
    ]
